// Generates lib/constants/ionicons.dart (+ the font asset) from the Ionicons
// font and glyph map that your React Native app already ships, so every icon
// is pixel-identical to the RN app.
//
//   dart run tool/gen_ionicons.dart <path-to-RN-project>
//   dart run tool/gen_ionicons.dart --json <Ionicons.json> --ttf <Ionicons.ttf>
//
// The RN project needs `node_modules` (run `npm install` there if missing); the
// files live in node_modules/@expo/vector-icons/**/{glyphmaps/Ionicons.json,Fonts/Ionicons.ttf}
import 'dart:convert';
import 'dart:io';

const _reserved = <String>{
  'assert', 'break', 'case', 'catch', 'class', 'const', 'continue', 'default',
  'do', 'else', 'enum', 'extends', 'false', 'final', 'finally', 'for', 'if',
  'in', 'is', 'new', 'null', 'rethrow', 'return', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'var', 'void', 'while', 'with',
};

void main(List<String> args) {
  String? json;
  String? ttf;

  if (args.length >= 2 && args.contains('--json')) {
    json = args[args.indexOf('--json') + 1];
    if (args.contains('--ttf')) ttf = args[args.indexOf('--ttf') + 1];
  } else if (args.isNotEmpty) {
    final root = Directory(args.first);
    final search = <Directory>[
      Directory('${root.path}/node_modules/@expo/vector-icons'),
      Directory('${root.path}/node_modules/react-native-vector-icons'),
    ];
    for (final dir in search.where((d) => d.existsSync())) {
      for (final e in dir.listSync(recursive: true, followLinks: false)) {
        final p = e.path.replaceAll('\\', '/');
        if (e is File && p.endsWith('/Ionicons.json') && json == null) json = e.path;
        if (e is File && p.endsWith('/Ionicons.ttf') && ttf == null) ttf = e.path;
      }
      if (json != null && ttf != null) break;
    }
  }

  if (json == null || ttf == null) {
    stderr.writeln('Could not find Ionicons.json / Ionicons.ttf.\n'
        'Usage: dart run tool/gen_ionicons.dart <path-to-RN-project>\n'
        '   (the RN project must have node_modules installed)\n'
        '   or: dart run tool/gen_ionicons.dart --json <file> --ttf <file>');
    exit(64);
  }

  final map = jsonDecode(File(json).readAsStringSync()) as Map<String, dynamic>;
  final names = map.keys.toList()..sort();
  final used = <String>{};
  final out = StringBuffer()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln('/// GENERATED by tool/gen_ionicons.dart from the RN app\'s Ionicons font.')
    ..writeln('/// Do not edit by hand — re-run the tool instead.')
    ..writeln('class Ionicons {')
    ..writeln('  Ionicons._();')
    ..writeln();

  for (final name in names) {
    var id = name.replaceAll('-', '_').replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
    if (RegExp(r'^[0-9]').hasMatch(id)) id = 'i_$id';
    if (_reserved.contains(id)) id = '${id}_';
    if (!used.add(id)) continue;
    final code = (map[name] as num).toInt();
    out.writeln("  static const IconData $id = IconData(0x${code.toRadixString(16)}, fontFamily: 'Ionicons');");
  }
  out.writeln('}');

  File('lib/constants/ionicons.dart').writeAsStringSync(out.toString());

  Directory('assets/fonts').createSync(recursive: true);
  File(ttf).copySync('assets/fonts/Ionicons.ttf');

  // Register the font in pubspec.yaml (once).
  final pubspec = File('pubspec.yaml');
  var text = pubspec.readAsStringSync();
  if (!text.contains('family: Ionicons')) {
    const marker = 'uses-material-design: true';
    if (!text.contains(marker)) {
      stderr.writeln('Add this under `flutter:` in pubspec.yaml yourself:\n'
          '  fonts:\n    - family: Ionicons\n      fonts:\n        - asset: assets/fonts/Ionicons.ttf');
    } else {
      text = text.replaceFirst(
        marker,
        '$marker\n  fonts:\n    - family: Ionicons\n      fonts:\n        - asset: assets/fonts/Ionicons.ttf',
      );
      pubspec.writeAsStringSync(text);
    }
  }

  stdout.writeln('OK: ${used.length} icons -> lib/constants/ionicons.dart, '
      'font -> assets/fonts/Ionicons.ttf, pubspec registered.\n'
      'Now run: flutter pub get && flutter run');
}
